# Generated by Django 3.1.7 on 2021-04-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210414_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review_image',
            old_name='reviews',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='usercoupon',
            old_name='coupons',
            new_name='coupon',
        ),
        migrations.RenameField(
            model_name='usercoupon',
            old_name='users',
            new_name='user',
        ),
    ]
