# Generated by Django 3.1.7 on 2021-04-15 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210415_0311'),
        ('orders', '0002_auto_20210414_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='orders',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_methods',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='shippinginformation',
            old_name='users',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupons',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_informations',
        ),
        migrations.RemoveField(
            model_name='order',
            name='statuses',
        ),
        migrations.RemoveField(
            model_name='order',
            name='users',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.shippinginformation'),
        ),
        migrations.AddField(
            model_name='order',
            name='statuse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.status'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
