# Generated by Django 3.2 on 2021-04-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210415_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
