# Generated by Django 3.1.7 on 2021-04-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.menu'),
        ),
        migrations.AlterField(
            model_name='option',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_fees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.shippingfee'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='shippingfee',
            name='minimum_free',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='shippingfee',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='main_categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.maincategory'),
        ),
        migrations.AlterField(
            model_name='subcategory_product',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterField(
            model_name='subcategory_product',
            name='sub_categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory'),
        ),
    ]
