# Generated by Django 3.1.7 on 2021-04-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210414_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='options',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discounts',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='options',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shipping_fees',
            new_name='shipping_fee',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_cateories',
            new_name='sub_cateory',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='main_categories',
            new_name='main_category',
        ),
        migrations.RenameField(
            model_name='subcategory_product',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='subcategory_product',
            old_name='sub_categories',
            new_name='sub_category',
        ),
    ]
