# Generated by Django 3.2 on 2021-04-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_sub_cateory_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincategory',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
